name: FreedomOpMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the FreedomOP server.
softdepend: [BukkitTelnet, WorldEdit, Essentials, BarAPI]
authors: [Madgeek1450, DarthSalamon, Camzie99, RobinGall2910, PieGuy7896]

# plugin.yml is no longer used to define commands.